### ISSUE TITLE
Not able to download the connector from store 

### ISSUE THREAD

**Issue by garimagarg86** [wso2-extensions/esb-connector-netsuite#10]
**Description:**
When I go to page "https://store.wso2.com/store/assets/esbconnector/details/84247167-9181-4175-864d-b8e2065188ff" and click on download connector, it fails to download the same.

Please fix the issue asap as we need the connectors otherwise we would have to recode the same again.

**Comment by garimagarg86** [comment]
Please fix the issue as we are on a very strict timeline.

**Comment by a2bgit** [comment]
what alternate are you using @garimagarg86

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3498
