### ISSUE TITLE
Some test cases failed while verify with EI 6.2.0.

### ISSUE THREAD

**Issue by kesavany** [wso2-extensions/esb-connector-netsuite#8]
**Description:**
Some test cases failed with the error 'You are not requesting the correct data center for your company! Please correct the host in the URL.' with the following APU URLs. https://webservices.na1.netsuite.com/services/NetSuitePort_2014_1
https://webservices.netsuite.com/services/NetSuitePort_2014_1
refer: https://stackoverflow.com/questions/25683169/netsuite-error-you-are-not-requesting-the-correct-data-center-for-your-company

wire log:
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "POST /services/NetSuitePort_2014_1 HTTP/1.1[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Content-Type: text/xml; charset=UTF-8[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "SOAPAction: "getAll"[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Transfer-Encoding: chunked[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Host: webservices.na1.netsuite.com[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Connection: Keep-Alive[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "User-Agent: Synapse-PT-HttpComponents-NIO[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "5ef[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,420] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:platformCore="urn:core_2014_1.platform.webservices.netsuite.com" xmlns:platformMsgs="urn:messages_2014_1.platform.webservices.netsuite.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Header><platformMsgs:preferences><platformMsgs:warningAsError/><platformMsgs:disableMandatoryCustomFieldValidation>{$ctx:disableMandatoryCustomFieldValidation}[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,421] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "                [\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,421] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "                            </platformMsgs:disableMandatoryCustomFieldValidation><platformMsgs:disableSystemNotesForCustomFields>{$ctx:disableSystemNotesForCustomFields}[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,421] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "                [\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,421] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "                            </platformMsgs:disableSystemNotesForCustomFields><platformMsgs:ignoreReadOnlyFields/></platformMsgs:preferences><platformMsgs:partnerInfo><platformMsgs:partnerId/></platformMsgs:partnerInfo><platformMsgs:applicationInfo><platformMsgs:applicationId/></platformMsgs:applicationInfo><platformMsgs:passport><platformCore:email>xxxxxxxxx</platformCore:email><platformCore:password>xxxxxxxx</platformCore:password><platformCore:account>TSxxxxx12</platformCore:account><platformCore:role internalId="" externalId="" type=""><platformCore:name/></platformCore:role></platformMsgs:passport></soapenv:Header><soapenv:Body><platformMsgs:getAll>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,421] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "                            <platformMsgs:record recordType="customer"/>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,421] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "                        </platformMsgs:getAll></soapenv:Body></soapenv:Envelope>[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,421] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "0[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,421] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "HTTP/1.1 200 OK[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Date: Tue, 17 Apr 2018 09:05:38 GMT[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Content-Type: text/xml[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "X-N-OperationId: db45a363-6b89-4561-839b-4864f959e876[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "NS_RTIMER_COMPOSITE: 205806275:706172746E6572733030362E70726F642E626F732E6E65746C65646765722E636F6D:80[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Set-Cookie: NS_ROUTING_VERSION=LEADING; path=/[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Set-Cookie: NS_VER=2018.1.0; path=/[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "P3P: CP="CAO PSAa OUR BUS PUR"[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Vary: User-Agent[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Keep-Alive: timeout=10, max=916[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,720] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Connection: Keep-Alive[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,721] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Transfer-Encoding: chunked[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,721] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,721] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "51b[\r][\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,722] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "<?xml version="1.0" encoding="UTF-8"?>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "    <soapenv:Body>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "        <soapenv:Fault>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "            <faultcode>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                soapenv:Server.userException[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "            </faultcode>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "            <faultstring>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                You are not requesting the correct data center for your company! Please correct the host in the URL.[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "            </faultstring>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "            <detail>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                <platformFaults:unexpectedErrorFault xmlns:platformFaults="urn:faults_2014_1.platform.webservices.netsuite.com">[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                    <platformFaults:code>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                        USER_ERROR[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                    </platformFaults:code>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                    <platformFaults:message>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                        You are not requesting the correct data center for your company! Please correct the host in the URL.[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                    </platformFaults:message>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                </platformFaults:unexpectedErrorFault>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                <ns1:hostname xmlns:ns1="http://xml.apache.org/axis/">[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                    partners006.prod.bos.netledger.com[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "                </ns1:hostname>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "            </detail>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "        </soapenv:Fault>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "    </soapenv:Body>[\n]"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-04-17 14:35:38,723] [EI-Core] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "</soapenv:Envelope>[

**Comment by anupama-pathirage** [comment]
Closing as this is EI test failures.
